# Generated by Django 4.0.2 on 2023-05-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_vehicle_vehicle_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vehicle_location',
        ),
    ]
