# Generated by Django 4.0.2 on 2023-05-12 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0008_vehicle_fuel_type_vehicle_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=models.TextField(default=1, unique=True, verbose_name='Vehicle Slug'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Booking Confirmed')),
                ('renter', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=models.SET('deleted'), to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=models.SET('deleted'), to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
