# Generated by Django 4.0.2 on 2023-05-17 06:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_remove_booking_payed_booking_is_terminated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='terminatebooking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehiclestatistics',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vehicles.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='terminatebooking',
            name='booking',
            field=models.OneToOneField(on_delete=models.SET('Deleted'), primary_key=True, serialize=False, to='vehicles.booking', verbose_name='Payment for booking'),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='vehicle_main',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vehicle', serialize=False, to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehiclestatistics',
            name='vehicle',
            field=models.OneToOneField(on_delete=models.SET('Deleted'), primary_key=True, serialize=False, to='vehicles.vehicle'),
        ),
    ]
