# Generated by Django 4.0.2 on 2023-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_remove_bookingdetails_id_remove_terminatebooking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes on delivery'),
        ),
    ]
