# Generated by Django 4.0.2 on 2023-06-04 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0015_alter_vehicle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='renter',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='terminatebooking',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vehicles.booking', verbose_name='Payment for booking'),
        ),
        migrations.AlterField(
            model_name='vehiclestatistics',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vehicles.vehicle'),
        ),
    ]
