# Generated by Django 4.0.2 on 2023-05-17 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vehicles', models.IntegerField(default=0, verbose_name='User Total Vehicles')),
                ('total_earnings', models.IntegerField(default=0, verbose_name='User Total Earnings')),
                ('total_expense', models.IntegerField(default=0, verbose_name='User Total Earnings')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
