# Generated by Django 4.0.2 on 2023-05-08 04:01

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, default=0, max_length=10, unique=True, validators=[apps.authentication.models.phone_validator], verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
