# Generated by Django 4.0.2 on 2023-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicle_vehicle_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='reg_no',
            field=models.CharField(max_length=20, unique=True, verbose_name='Vehicle Registration Number'),
        ),
    ]
