# Generated by Django 4.0.2 on 2023-05-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('EV', 'Electric Vehicle'), ('PF', 'Petrol Fuel'), ('DF', 'Diesel Fuel'), ('HV', 'Hybrid Electric and Fuel'), ('HY', 'Hydrogen Power')], default='PF', max_length=200, verbose_name='Fuel Type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(default=1, verbose_name='Mileage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('AT', 'Automatic'), ('MN', 'Manual'), ('AM', 'Automatic Manual')], default='MN', max_length=200, verbose_name='Transmission Type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicles.location', verbose_name='Vehicle City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
    ]
