# Generated by Django 4.0.2 on 2023-05-15 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_vehicle_slug_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Booking End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Booking Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_total_days',
            field=models.IntegerField(default=3, verbose_name='Booking Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payed',
            field=models.BooleanField(default=False, null=True, verbose_name='Booking is Payed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(default=False, null=True, verbose_name='Booking Confirmed'),
        ),
    ]
