# Generated by Django 4.0.2 on 2023-05-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_alter_booking_booking_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payed',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_terminated',
            field=models.BooleanField(default=False, null=True, verbose_name='Booking is Terminated'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_total_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Booking Duration'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='security_deposit',
            field=models.IntegerField(verbose_name='Security Deposit'),
        ),
        migrations.CreateModel(
            name='VehicleStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('total_earnings', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Total Earnings till Date')),
                ('total_expense', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Total Earnings till Date')),
                ('total_km_tracked', models.IntegerField(default=0, verbose_name='Total KMs travelled so far')),
                ('total_rentals', models.IntegerField(default=0, verbose_name='Total Rentals Till Date')),
                ('total_turnover', models.IntegerField(default=0, verbose_name='Vehicle Turnover')),
                ('average_expense_per_day', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Average Daily Expense')),
                ('average_expense_per_rental', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Average Expense per Rental')),
                ('average_expense_per_distance', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Average Expense per Distance')),
                ('average_income_per_day', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Average Daily Income')),
                ('average_income_per_rental', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Average Income per Rental')),
                ('average_income_per_distance', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Average Income per Distance')),
                ('average_turnover_per_day', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Average Daily Turnover')),
                ('average_turnover_per_rental', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Average Turnover per Rental')),
                ('average_turnover_per_distance', models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Average Turnover per Distance')),
                ('vehicle', models.OneToOneField(on_delete=models.SET('Deleted'), to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TerminateBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('end_type', models.IntegerField(choices=[(332, 'Payment'), (232, 'Cancel')], verbose_name='Termination Type')),
                ('amount', models.IntegerField(default=0, verbose_name='Payment Amount')),
                ('handshake', models.BooleanField(default=False, verbose_name='Renter Rentee Handshake')),
                ('booking', models.OneToOneField(on_delete=models.SET('Deleted'), to='vehicles.booking', verbose_name='Payment for booking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('odometer_reading_before', models.IntegerField(blank=True, null=True, verbose_name='Odometer Reading at Start of Trip')),
                ('odometer_reading_after', models.IntegerField(blank=True, null=True, verbose_name='Odometer Reading at End of Trip')),
                ('notes', models.TextField(verbose_name='Notes on delivery')),
                ('booking', models.OneToOneField(on_delete=models.SET('Deleted'), to='vehicles.booking', verbose_name='Booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
