# Generated by Django 4.0.2 on 2023-10-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_alter_booking_renter_alter_booking_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-creation_date', '-modification_date']},
        ),
        migrations.AlterModelOptions(
            name='bookingdetails',
            options={'ordering': ['-creation_date', '-modification_date']},
        ),
        migrations.AlterModelOptions(
            name='terminatebooking',
            options={'ordering': ['-creation_date', '-modification_date']},
        ),
        migrations.AlterModelOptions(
            name='vehicledetails',
            options={'ordering': ['-creation_date', '-modification_date']},
        ),
        migrations.AlterModelOptions(
            name='vehiclestatistics',
            options={'ordering': ['-creation_date', '-modification_date']},
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='booking_details_set', serialize=False, to='vehicles.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='terminatebooking',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='terminate_bookings_set', serialize=False, to='vehicles.booking', verbose_name='Payment for booking'),
        ),
        migrations.AlterField(
            model_name='vehiclestatistics',
            name='total_expense',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, verbose_name='Total Expense till Date'),
        ),
    ]
